namespace ProjectMMOConfigurator.Models
{
    /// <summary>
    ///  NOTE that the min and max is for information purposes only, the UI does not enforce it.
    /// </summary>
    internal static class Attributes
    {
        public static Dictionary<string, (double min, double max)> Values = new()
        {
                { "additionalentityattributes:generic.height", (0.06, 16) },
                { "additionalentityattributes:generic.hitbox_height", (0.06, 16) },
                { "additionalentityattributes:generic.hitbox_width", (0.06, 16) },
                { "additionalentityattributes:generic.hitbox_scale", (0.06, 16) },
                { "additionalentityattributes:generic.lava_speed", (0, 1) },
                { "additionalentityattributes:generic.magic_protection", (0, 1024) },
                { "additionalentityattributes:generic.mob_detection_range", (1, 1024) },
                { "additionalentityattributes:generic.model_height", (0.06, 16) },
                { "additionalentityattributes:generic.model_width", (0.06, 16) },
                { "additionalentityattributes:generic.model_scale", (0.06, 16) },
                { "additionalentityattributes:generic.water_speed", (0, 1) },
                { "additionalentityattributes:generic.width", (0.5, 3) },
                { "additionalentityattributes:player.bonus_loot_count_rolls", (0, 1024) },
                { "additionalentityattributes:player.bonus_rare_loot_rolls", (0, 128) },
                { "additionalentityattributes:player.collection_range", (-64, 64) },
                { "additionalentityattributes:player.critical_bonus_damage", (0, 10000) },
                { "additionalentityattributes:player.dropped_experience", (0, 1024) },
                { "additionalentityattributes:player.lava_visibility", (0, 1024) },
                { "additionalentityattributes:player.water_visibility", (0, 1024) },
                { "allthearchanistgear:allthearchanistgear.spectral_sight", (0, 64) },
                { "apothic_attributes:armor_pierce", (0, 1000) },
                { "apothic_attributes:armor_shred", (0, 200) },
                { "apothic_attributes:arrow_damage", (0, 100) },
                { "apothic_attributes:arrow_velocity", (0, 100) },
                { "apothic_attributes:cold_damage", (0, 1000) },
                { "apothic_attributes:crit_chance", (0, 1000) },
                { "apothic_attributes:crit_damage", (-1, 1024) },
                { "apothic_attributes:current_hp_damage", (0, 100) },
                { "apothic_attributes:dodge_chance", (0, 100) },
                { "apothic_attributes:draw_speed", (0, 400) },
                { "apothic_attributes:elytra_flight", (0, 1) },
                { "apothic_attributes:experience_gained", (0, 1000000) },
                { "apothic_attributes:fire_damage", (0, 1000) },
                { "apothic_attributes:ghost_health", (0, 100) },
                { "apothic_attributes:healing_received", (0, 1000000) },
                { "apothic_attributes:life_steal", (0, 1000) },
                { "apothic_attributes:mining_speed", (0, 1000) },
                { "apothic_attributes:overheal", (0, 1000) },
                { "apothic_attributes:projectile_damage", (0, 1000) },
                { "apothic_attributes:prot_pierce", (0, 34) },
                { "apothic_attributes:prot_shred", (0, 100) },
                { "ars_nouveau:ars_elemental.perk.summon_power", (0, 10000) },
                { "ars_nouveau:ars_nouveau.perk.drygmy", (0, 1) },
                { "ars_nouveau:ars_nouveau.perk.feather", (0, 1) },
                { "ars_nouveau:ars_nouveau.perk.mana_regen", (0, 100) },
                { "ars_nouveau:ars_nouveau.perk.max_mana", (0, 10000) },
                { "ars_nouveau:ars_nouveau.perk.saturation", (0, 1000) },
                { "ars_nouveau:ars_nouveau.perk.spell_damage", (0, 10) },
                { "ars_nouveau:ars_nouveau.perk.wixie", (0, 1) },
                { "artifacts:generic.attack_burning_damage", (0, 60) },
                { "artifacts:generic.drinking_speed", (0, double.MaxValue) },
                { "artifacts:generic.eating_speed", (0, double.MaxValue) },
                { "artifacts:generic.flatulence", (0, 1) },
                { "artifacts:generic.invincibility_ticks", (0, 1024) },
                { "artifacts:generic.mount_speed", (0, 1024) },
                { "artifacts:generic.movement_speed_on_snow", (0, 1024) },
                { "artifacts:generic.slip_resistance", (0, 1) },
                { "artifacts:generic.sprinting_speed", (0, 1024) },
                { "artifacts:generic.spriting_step_height", (0, 10) },
                { "artifacts:player.entity_experience", (0, 100) },
                { "artifacts:player.villager_reputation", (0, 1024) },
                { "caelus:fall_flying", (0.1, 1) },
                { "eternal_starlight:generic.ether_resistance", (0, 1) },
                { "eternal_starlight:generic.throw_potion_distance", (0, 5) },
                { "irons_spellbooks:blood_magic_resist", (-100, 100) },
                { "irons_spellbooks:blood_spell_power", (-100, 100) },
                { "irons_spellbooks:cast_time_reduction", (-100, 100) },
                { "irons_spellbooks:casting_movespeed", (0, 100) },
                { "irons_spellbooks:cooldown_reduction", (-100, 100) },
                { "irons_spellbooks:eldritch_magic_resist", (-100, 100) },
                { "irons_spellbooks:eldritch_spell_power", (-100, 100) },
                { "irons_spellbooks:ender_magic_resist", (-100, 100) },
                { "irons_spellbooks:ender_spell_power", (-100, 100) },
                { "irons_spellbooks:fire_magic_resist", (-100, 100) },
                { "irons_spellbooks:fire_spell_power", (-100, 100) },
                { "irons_spellbooks:ice_magic_resist", (-100, 100) },
                { "irons_spellbooks:ice_spell_power", (-100, 100) },
                { "irons_spellbooks:lightning_magic_resist", (-100, 100) },
                { "irons_spellbooks:lightning_spell_power", (-100, 100) },
                { "irons_spellbooks:evocation_magic_resist", (-100, 100) },
                { "irons_spellbooks:evocation_spell_power", (-100, 100) },
                { "irons_spellbooks:holy_magic_resist", (-100, 100) },
                { "irons_spellbooks:holy_spell_power", (-100, 100) },
                { "irons_spellbooks:mana_regen", (0, 2000) },
                { "irons_spellbooks:max_mana", (0, 1000000) },
                { "irons_spellbooks:nature_magic_resist", (-100, 100) },
                { "irons_spellbooks:nature_spell_power", (-100 , 100) },
                { "irons_spellbooks:spell_power", (-100 , 100) },
                { "irons_spellbooks:spell_resist", (-100 , 100) },
                { "irons_spellbooks:summon_damage", (-100 , 100) },
                { "justdirethings:phase", (0, 1) },
                { "minecolonies:mc_mob_damage", (0, 10) },
                { "minecraft:generic.armor", (0, 1000000) },
                { "minecraft:generic.armor_toughness", (0, 1000000) },
                { "minecraft:generic.attack_damage", (0, 1000000) },
                { "minecraft:generic.attack_knockback", (0, 1000000) },
                { "minecraft:generic.attack_speed", (0, 1024) },
                { "minecraft:generic.buring_time", (0, 1024) },
                { "minecraft:generic.explosion_knockback_resistance", (0, 1) },
                { "minecraft:generic.fall_damage_multiplier", (0, 100) },
                { "minecraft:generic.flying_speed", (0, 1) },
                { "minecraft:generic.follow_range", (0, 100) },
                { "minecraft:generic.gravity", (-1, 1) },
                { "minecraft:generic.knockback_resistance", (0, 100) },
                { "minecraft:generic.luck", (-1024, 1024) },
                { "minecraft:generic.max_absorption", (0, 2048) },
                { "minecraft:generic.max_health", (0, 1000000) },
                { "minecraft:generic.movement_speed", (0, 1024000) },
                { "minecraft:generic.movement_efficiency", (0, 1) },
                { "minecraft:generic.oxygen_bonus", (0, 1024) },
                { "minecraft:generic.safe_fall_distance", (-1024, 1024) },
                { "minecraft:generic.scale", (0.1, 10) },
                { "minecraft:generic.step_height", (0, 10) },
                { "minecraft:generic.jump_strength", (0, 32) },
                { "minecraft:generic.water_movement_efficiency", (0, 1) },
                { "minecraft:player.block_break_speed", (0, 1024) },
                { "minecraft:player.block_interaction_range", (0, 64) },
                { "minecraft:player.entity_interaction_range", (0, 64) },
                { "minecraft:player.mining_efficiency", (0, 1024) },
                { "minecraft:player.sneaking_speed", (0, 1) },
                { "minecraft:player.submerged_mining_speed", (0, 20) },
                { "minecraft:player.sweeping_damage_ratio", (0, 1) },
                { "minecraft:zombie.spawn_reinforcements", (0, 1) },
                { "modern_industrealization:infinite_damage", (0, 1) },
                { "modern_industrealization:quantum_armor", (0, 1) },
                { "neoforge:creative_flight", (0, 1) },
                { "neoforge:nametag_distance", (0, 100) },
                { "neoforge:swim_speed", (0, 1024000) },
                { "not_enough_glyphs:not_enough_glyphs.perk.mana_discount", (0, double.MaxValue) },
                { "pmmo:vein_amount", (0, double.MaxValue) },
                { "pmmo:vein_capacity", (0, 100) },
                { "pmmo:vein_charge_rate", (0, int.MaxValue) },
                { "xycraft_machines:hover_flight", (0, 1) }
            };
    }
}
